### ISSUE TITLE
Custom Entity System

### ISSUE THREAD

**Issue by UltimaOath** [ArcanePlugins/LevelledMobs#317]
Was working on this behind the scenes for LM4, but might as well drop it here for whomever wants the mantle. It was my attempt at a Custom Entity making tool, prob. for it's own file `customentities.yml` or similar.  
I wanted to find a way that we could make some baby steps into the custom entity field, and help reduce our dependency on 3rd party plugins which require more solution chasing than they're worth in my opinion. I believe this might be some of the first baby steps if possible:

Essentially when an entity of the entitytype spawns, should all checks say this should be a custom entity, we would override the default attributes of that entity, apply it's unique name, and level it under whatever rules it would have levelled under otherwise, again unless the custom-entity condition is checked and that custom entity would get it's own multipliers.

```yaml
# Any entity can be customized, even if otherwise
# LM would not level them (custom passive values, etc.)

custom-entities:
# Any attribute not listed will assume the EntityType's default value.

  custom_AlphaZombie:
    entity_type: ZOMBIE
    entity_name: 'Alpha Zombie'
    base_attributes: #These settings set the value of the default base attributes for the custom entity.
      max-health: 30-35
      movement-speed: 0.25-0.26
      attack-damage: 5.0-5.5
      armor-bonus: 2.0-3.0
      armor-toughness: 0-1.0
      zombie-spawn-reinforcements: 0.25
    use-droptable-id: dropTable #establishes additional drops to this CustomEntity separate from any other setting; does not override default

  custom_BetaZombie:
    entity_type: ZOMBIE
    entity_name: 'Beta Zombie'
    base_attributes:
      max-health: 100
      movement-speed: 0.10
      attack-damage: 10
      armor-bonus: 5
      armor-toughness: 5
      zombie-spawn-reinforcements: 1.0


# This is how it would be implemented through the rules system. Since the entitytype is listed for each custom entity, the `conditions:` check for entities should not be required. We can however make limitations such as biomes, time of day, etc. This would allow for a varied array of entities that have different skillsets.
  alpha-zombie-rule:
    enabled: true
    description: 'CustomEntity - AlphaZombie'
    conditions:
      chance: 0.5
    apply-settings:
      use-custom-entity: ['custom_AlphaZombie']

# I believe we could also include a condition check to determine if the entity was one of the custom entities, and then apply different multipliers to those entities should we need to.
conditions:
  custom-entities: ['custom_BetaZombie']
apply-settings:
  multipliers:
    etc:
```

**Comment by UltimaOath** [comment]
**Entity Combat Tree (ECT)**

This concept is being developed as an expansion to the above 'Soft CustomEntity Reconstruction'.

```yaml
custom-entities:
  custom_GammaZombie: #Start of 'Custom Entity' called 'GammaZombie' for example.

# Section One
    entity_combat-tree:

# Section Two
      entity_health:
        100: #Activate upon tracking a player if entity is at 100% health.
          command: ['']
        50:
          effect:
            BLINDNESS: 3
              limit: 2
        15:
          stack: false
          effect:
            HEALTH_BOOST: 5
        0: #Activate upon entity reaching 0% health.
          effect:
            HEAL: 10



# Section Three
# References:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
# Activate upon the entity performing the specific damage event
      entity_damage-event:
        ENTITY_ATTACK: #Activate upon EntityDamageEvent of same name
          chance: 0.2
          limit: 5
          effect:
            WEAKNESS: 5
              limit: 2


# Section Four
# References:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.html#getDamage()
# Activate upon the entity performing a specific amount of damage during an event
      entity_damage-amount:
        stack: false
        4: #Activate upon this amount or higher
          effect:
        8: #Activate upon reaching this amount or higher
          command:


# Section Five
# 
# Activate on chance and timers alone.
      entity_abilities:
        effect:
          WITHER: 2
          chance: 0.01
          limit: 1
        command: ['say %player% Stop Hitting Me!']
```

**Section One - The Abilities**

Currently I do not have many concepts for what should occur if X event occurs. I am currently using `command` and `effect`.  
`command` functions in similar way to how command works in CustomDrops; perform established command.  
`effect` uses the [https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html) as a reference when populating possible effects, and it's duration time. Below represents the layout, where X is the duration of effect.

```yaml
          effect:
            POTION-EFFECT-TYPE: X
```

Each `command` and `effect` can include a `chance` component as to whether this would always occur or occur at random chance. This is separate from any chance or conditions established by implementing the entity via a Custom Rule.

```yaml
      entity_damage-event:
        ENTITY_ATTACK: #Activate upon EntityDamageEvent of same name
          chance: 0.2
          limit: 5 #Master Limit for event-type
          effect:
            WEAKNESS: 5
              limit: 2 #Limit for specific effect/command
```

There is also the `limit` function, which would prevent the entity from performing a specific event endlessly. There are two options for calculating limits on events: a limit set to apply to the checked event or amount, as well as a method of limiting specific effects.

If a limit is set for the condition, for example `ENTITY_ATTACK`, then that means any effect or command under that entity could only run X times. If a limit is set for the specific event, then that particular event would have a limited number of runs compared to any other effect. It will never occur more times than the 'master limit' as demonstrated above. (I'm tired so didn't clarify this, but can at a later date; lots to write!)

There is also the `stack: false` config option. I believe by default this should be set to true.  
By default, the `entity_health` and `entity_damage-amount` sections would stack all possible options and process them together. For example, using the config demo above (assuming `stack: true`), if a newly spawned full health entity approached me to attack, then all options listed on the entity\_health would be lumped together from 100% health to 0% health and be processed together. As an entity looses health, they begin to loose access to their higher-health abilities.

A similar ability would occur with `entity_damage-amount`, using the config demo above (assuming `stack: true`), if an entity performed 10 damage to a player, then it would process all damage events from 10 damage down to 0.

With `stack: false`, both sections would be processed slightly differently:  
`entity_health` and `entity_damage-amount` would both instead only use the highest possible option.

If an entity approaches the same player with full health, then only the full health effects and commands would be accessible. As the entity reduces in health, the higher health tiers become inaccessible as they go down the tiers until they run out of all health. Each tier would activate it's own set of conditions.

If the same entity was to perform 10hp damage on the same player, then the closest tier would be `8` in the demo, so only that tier would be accessible. This would be useful for establishing 'special' attacks based on the entity's strength.

These statistics could be stored in the PCD of that particular entity, and reset after a set amount of time after entity stops tracking player (similar to how we prevent repeat updates in Player Levelling). Unless there are better solutions available. I am also actively looking for other potential 'events' to activate, but for now the two would be a good starting point.

**Section Two - Entity Health Tree**

This section represents a condition check on the entity's remaining health points.

```yaml
# Section Two
      entity_health:
        100:
          stack: false
          command: 'say %player% Get off my property!'
            limit: 1
        50:
          effect:
            BLINDNESS: 3
              limit: 2
        15:
          stack: false
          effect:
            HEALTH_BOOST: 5
            chance: 0.05
        0:
          effect:
            HEAL: 10
```

In the above example, I am checking the entity's health at `100%`, `50%`, `15%`, and `0%`.  
When an entity's health is checked at `100%`, as entities spawn at full health typically, this would not activate until an entity has started tracking a player in hostile manner. When an entity is killed, the `0%` events are performed. This is the only health value which cannot be stacked, as it occurs when the entity has already died, and thus is a final 'event' to occur upon the entity's death.

If `chance` is not specified, it is assumed 100% to occur, due to the nature of the system.

All possible options would be collected together (excluding any particular health option which has `stack: false`), and the chances and probabilities are processed out. Effects/Commands occur, and the battle continues. This health check can be performed as a player attacks the entity, upon successful hit, determine remaining hp and process it's abilities.

Once the entity goes to anywhere between 0-99% of total health, they would lose access to the `100%` tier of commands or effects to join the possible processing, again along with any other `stack: false` set ability. Once it goes to 0-49, the same effect occurs but to the top two options.

So using the example, I would regard it as follows:  
"An entity approaches a player and attacks. This entity performs the say command upon noticing the player. "

**Section Three - Entity Damage Event Tree**

asd

**Section Four - Entity Damage Amount Tree**

**asd\*\***Entity Combat Tree (ECT)\*\*

This concept is being developed as an expansion to the above 'Soft CustomEntity Reconstruction'.

```yaml
custom-entities:
  custom_GammaZombie: #Start of 'Custom Entity' called 'GammaZombie' for example.

# Section One
    entity_combat-tree:

# Section Two
      entity_health:
        100: #Activate upon tracking a player if entity is at 100% health.
          command: ['']
        50:
          effect:
            BLINDNESS: 3
              limit: 2
        15:
          stack: false
          effect:
            HEALTH_BOOST: 5
        0: #Activate upon entity reaching 0% health.
          effect:
            HEAL: 10



# Section Three
# References:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
# Activate upon the entity performing the specific damage event
      entity_damage-event:
        ENTITY_ATTACK: #Activate upon EntityDamageEvent of same name
          chance: 0.2
          limit: 5
          effect:
            WEAKNESS: 5
              limit: 2


# Section Four
# References:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.html#getDamage()
# Activate upon the entity performing a specific amount of damage during an event
      entity_damage-amount:
        stack: false
        4: #Activate upon this amount or higher
          effect:
        8: #Activate upon reaching this amount or higher
          command:


# Section Five
# Activate on chance and timers alone.
      entity_abilities:
        effect:
          WITHER: 2
          chance: 0.01
          limit: 1
        command: ['say %player% Stop Hitting Me!']
```

**Section One - The Abilities**

Currently I do not have many concepts for what should occur if X event occurs. I am currently using `command` and `effect`.  
`command` functions in similar way to how command works in CustomDrops; perform established command.  
`effect` uses the [https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html) as a reference when populating possible effects, and it's duration time. Below represents the layout, where X is the duration of effect.

```yaml
          effect:
            POTION-EFFECT-TYPE: X
```

Each `command` and `effect` can include a `chance` component as to whether this would always occur or occur at random chance. This is separate from any chance or conditions established by implementing the entity via a Custom Rule.

```yaml
      entity_damage-event:
        ENTITY_ATTACK: #Activate upon EntityDamageEvent of same name
          chance: 0.2
          limit: 5 #Master Limit for event-type
          effect:
            WEAKNESS: 5
              limit: 2 #Limit for specific effect/command
```

There is also the `limit` function, which would prevent the entity from performing a specific event endlessly. There are two options for calculating limits on events: a limit set to apply to the checked event or amount, as well as a method of limiting specific effects.

If a limit is set for the condition, for example `ENTITY_ATTACK`, then that means any effect or command under that entity could only run X times. If a limit is set for the specific event, then that particular event would have a limited number of runs compared to any other effect. It will never occur more times than the 'master limit' as demonstrated above. (I'm tired so didn't clarify this, but can at a later date; lots to write!)

There is also the `stack: false` config option. I believe by default this should be set to true.  
By default, the `entity_health` and `entity_damage-amount` sections would stack all possible options and process them together. For example, using the config demo above (assuming `stack: true`), if a newly spawned full health entity approached me to attack, then all options listed on the entity\_health would be lumped together from 100% health to 0% health and be processed together. As an entity looses health, they begin to loose access to their higher-health abilities.

A similar ability would occur with `entity_damage-amount`, using the config demo above (assuming `stack: true`), if an entity performed 10 damage to a player, then it would process all damage events from 10 damage down to 0.

With `stack: false`, both sections would be processed slightly differently:  
`entity_health` and `entity_damage-amount` would both instead only use the highest possible option.

If an entity approaches the same player with full health, then only the full health effects and commands would be accessible. As the entity reduces in health, the higher health tiers become inaccessible as they go down the tiers until they run out of all health. Each tier would activate it's own set of conditions.

If the same entity was to perform 10hp damage on the same player, then the closest tier would be `8` in the demo, so only that tier would be accessible. This would be useful for establishing 'special' attacks based on the entity's strength.

These statistics could be stored in the PCD of that particular entity, and reset after a set amount of time after entity stops tracking player (similar to how we prevent repeat updates in Player Levelling). Unless there are better solutions available. I am also actively looking for other potential 'events' to activate, but for now the two would be a good starting point.

**Section Two - Entity Health Tree**

This section represents a condition check on the entity's remaining health points.

```yaml
# Section Two
      entity_health:
        100:
          stack: false
          command: 'say %player% Get off my property!'
            limit: 1
        50:
          effect:
            BLINDNESS: 3
              limit: 2
        15:
          stack: false
          effect:
            HEALTH_BOOST: 5
            chance: 0.05
        0:
          effect:
            HEAL: 10
            chance: 0.2
```

In the above example, I am checking the entity's health at `100%`, `50%`, `15%`, and `0%`.  
When an entity's health is checked at `100%`, as entities spawn at full health typically, this would not activate until an entity has started tracking a player in hostile manner. When an entity is killed, the `0%` events are performed. This is the only health value which cannot be stacked, as it occurs when the entity has already died, and thus is a final 'event' to occur upon the entity's death.

If `chance` is not specified, it is assumed 100% to occur, due to the nature of the system.

All possible options would be collected together (excluding any particular health option which has `stack: false`), and the chances and probabilities are processed out. Effects/Commands occur, and the battle continues. This health check can be performed as a player attacks the entity, upon successful hit, determine remaining hp and process it's abilities.

Once the entity goes to anywhere between 0-99% of total health, they would lose access to the `100%` tier of commands or effects to join the possible processing, again along with any other `stack: false` set ability. Once it goes to 0-49, the same effect occurs but to the top two options.

https://i.ibb.co/rw01B3z/Untitled.png

**Section Three - Entity Damage Event Tree**

This section represents a condition check on the entity's method of attack. Due to my lack of knowledge on how entity's attack, I made the section a bit flexible. Will take research to determine the best 'defaults' to present to people.

```yaml
      entity_damage-event:
        ENTITY_ATTACK: #Activate upon EntityDamageEvent of same name
          chance: 0.2
          limit: 5
          effect:
            WEAKNESS: 5
              limit: 2
```

Here I am referencing [https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html) when selecting the damage-event. When this event occurs from the entity, any effects/commands are performed using the same structure as demonstrated above, specifically regarding the limits and arrangement.

This is a much shorter section since the rest of the system is described above.

**Section Four - Entity Damage Amount Tree**

This section represents a condition check on the amount of damage an entity just performed against a player. 

```yaml
      entity_damage-amount:
        stack: false
        4: #Activate upon this amount or higher
          effect:
        8: #Activate upon reaching this amount or higher
          command:
```

Here I am referencing [https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.html#getDamage()](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.html#getDamage()) when determining the amount of damage caused. I am unsure what this value can be, so used regular health amounts as the example. Will require research to find good/valid default values.

Just like the other sections, this uses the same system of limits and arrangement as above.

**Section Five - Entity Ability Tree**

This section represents pure abilities that are potentially performed on a timer system during combat.

```yaml
      entity_abilities:
        effect:
          WITHER: 2
          chance: 0.05
          limit: 1
          timer: 10
        command: ['tellraw %player% ["",{"text":"Attacking %displayname%","color":"red"},{"text":": Prepare to DIE!"}]']
```

This section would 'activate' upon the entity tracking the player AND being within X blocks of player (unsure if this is too resource intensive; could limit to tracking initiation or after first entity landed hit; can research effects using different methods). Once activated, a timer will begin and all abilities would be evaluated at the end of the timer. Whether it runs or not, the timer resets and won't try again until the next time it reaches the count for the possible ability. If no timer is set, use a default internal of perhaps 10 for safety sake?

Can elaborate further, but exhausted. If needed will do once the project gets off the ground.

**Comment by UltimaOath** [comment]
Updated first post with LM4 implementation:
Condition check to apply to the appropriate entity/ies desired. 

```yaml
  actions:
    construct:   # The system which begins a listing of constructed entities
      custom_AlphaZombie:   # The name of the entity for reference in code/debug/etc.
        entity_name: 'Alpha Zombie'   # What would be used for the entity's name as if it were vanilla name
        base_attributes: #These settings set the value of the default base attributes for the custom entity. Ranged values select a random amount between the two.
          max-health: 30-35
          movement-speed: 0.25-0.26
          attack-damage: 5.0-5.5
          armor-bonus: 2.0-3.0
          armor-toughness: 0-1.0
          zombie-spawn-reinforcements: 0.25
          xp-drop: 25   # amount of XP that would drop at level 1/unlevelled version of this entity.
        use-droptable-id: dropTable # references a drop table of the same name, used to replace/override the entities' drops. If not specified, uses the default entity drops.

      custom_BetaZombie:
        entity_name: 'Beta Zombie'
          base_attributes:
            max-health: 100
            movement-speed: 0.10
            attack-damage: 10
            armor-bonus: 5
            armor-toughness: 5
            zombie-spawn-reinforcements: 1.0
```
      
Could also include condition check by something similar to `construct-entity: ['']`

**Comment by lokka30** [comment]
Being brainstormed in the demo files

**Comment by lokka30** [comment]
@UltimaOath @stumper66 

# LM4 Entity Templates

## About

This system allows admins to configure a named template of stats a mob will receive upon application of that template.
Essentially, the Entity Template System allows admins to spawn in 'custom entities'.

> Note that the current implementation idea described below *does not add any new features*, it just utilises the capabilities of the Functions system. The idea of the Entity Templates system was conceptualised by Oath, naming it the "Soft CustomEntity Reconstruction System", in the LM3 era. This idea takes a different approach to Oath's original idea, as LM4 has added an additional layer of logic – functions – to LM3's Rules system. Therefore, it accomodates the entity templates without it requiring a special section. 

## Configuration

###### `settings.yml`

```yaml
functions:
  - function: "alpha-zombie-template"
    processes:
      - process: "apply-template"
        do:
          - action: "set-buffs"
            use-presets: [ "extreme-challenge" ]
          - action: "set-packet-label"
            formula: "&fLvl. %entity-level% &c&lAlpha Zombie"
            visibility-methods: ["TARGETED", "ATTACKED", "MELEE"]
            visibility-duration: 10
          - action: "set-death-label"
            formula: "&fLvl. %entity-level% &c&lAlpha Zombie"

```

## Usage

### Via `/lm summon`

The structure of the `summon` sub-command, as of writing, is unknown. Therefore, a guaranteed syntax cannot be provided.

However, the `summon` sub-command should allow a list of functions to be called upon the summoning of the mob.

### Via an `LmFunction`

Simply call the template function:

```yaml
- action: "run-function"
  id: "alpha-zombie-template"
```

The mob in the context of that function call will then receive the template's stats.
