### ISSUE TITLE
LM4 Variable Levelling

### ISSUE THREAD

**Issue by UltimaOath** [ArcanePlugins/LevelledMobs#322]
LM4 will introduce an upgrade to LM3's Player Levelling – it will now be renamed to Variable Levelling for LM4.

- [x] Design
- [ ] Implement
  - [ ] Add support for vanished players #387 

Original, outdated idea:

<details>

<summary>Click to toggle view</summary>

```yaml
    strategies:
      player-levelling:
        match-level: true
        use-player-max-level: false
        player-level-scale: 1.0
        level-cap: 30
        tiers:
          1-15: 1-10
          16-30: 11-20
          31-45: 21-25
        variable: '%level%'

        max-nearby-players: 1
        max-distance-from-entity: 100
        relevel-timer: 5000
```

A method to use multiple nearby players, the default values are presented above.

`max-nearby-players: 1` | This setting determines the X closest players to the entity to use for calculating the entities' level, by taking the value of the individual players' variable and producing an average amount.

`max-distance-from-entity: 100` | I believe that this config option would remove player-levelling from the the settings.yml config `async-task-max-blocks-from-player:`, which is where I presume the distance comes from. This may work better as a reduced value for a default, such as `32` instead of `100`.

`relevel-timer: 5000` | I believe that this config option would remove player-levelling from the settings.yml config `player-levelling-relevel-min-time:` ; would function the same way. If timer is set to `0`, then only one relevel will be performed.

</details>
