### ISSUE TITLE
Add 'Titles' (prefix and/or suffix system) to Nametags

### ISSUE THREAD

**Issue by UltimaOath** [ArcanePlugins/LevelledMobs#325]
```yaml
  apply-settings:

    titles:
      prefix: # %p-title%
        kill_reward: true
          - 'Death '
          - 'Stalking '
          - 'Hungry '
      suffix: # %s-title%
        kill_reward: true
          - ' the Black-Thorn'
          - ' the Lurker'
          - ' the Cave Rat'
          - ' Bloodstoker'
          - ' Face-Eater'
```

Taking inspiration from the Nemesis system from Shadow of Mordor, a title is randomly selected and then applied to an entity via a `%title%` tag in the nametag:

EDIT: Updated to include the idea of prefix-suffix.

`nametag: '&8&l༺ %tiered%Lvl %mob-lvl%&8 | &f%p-title%%displayname%%s-title%&8 | &f%entity-health-rounded%&8/&f%entity-max-health-rounded% %tiered%%heart_symbol% &8&l༻'`

If `kill_reward: true`, then the title will only be given to an entity AFTER it has killed a player.

This makes for an interesting way to distinguish between the entities. Adds humor to the death messages with their titled' name, the player can locate the entity that actually killed them for revenge, or another player can stroll by a field of entities that kicked player butt. Otherwise, it's an interesting way to add flair to entities making them a bit more unique.
