### ISSUE TITLE
Increase Damage to Shields by Multiplier

### ISSUE THREAD

**Issue by UltimaOath** [ArcanePlugins/LevelledMobs#329]
```yaml
  apply-settings:
    multipliers:
      shield-damage: 1.0   # 100% increase in damage to shields at maxLevel
```

This setting references:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/EntityEffect.html#SHIELD_BLOCK

When an entity hits a shield, the damage to the shield can be increased by a percentage.
