### ISSUE TITLE
Allow setting a custom drop to use the left or right hand (as a percentage).

### ISSUE THREAD

**Issue by UltimaOath** [ArcanePlugins/LevelledMobs#333]
```yaml
  - DIAMOND_SWORD:
      equipped: true
      only-drop-if-equipped: true
      right-hand: 0.50

  - DIAMOND_AXE:
      left-hand: true
```

The suggestion of adding the config options `right-hand:` and `left-hand:` into the CustomDrops system. They would function with `true` or `false`, and `0.0` -> `1.0` for a chance to occur. If conflicting, the last in the stack would win. The config would only work if the item would have been equipped.

Referencing:  
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/EntityEquipment.html#setItemInMainHand(org.bukkit.inventory.ItemStack)

`setItemInMainHand` and `setItemInOffHand`

**Comment by mA0w0** [comment]
I felt I needed this as well.

I felt that the function implemented was not enough if I wanted the skeleton to have an arrow with an effect.
Skeletons with arrows in both hands will spawn in rare cases, even when the bow equip rate is set to 100%.

```
SKELETON:
  - usedroptable: bow_weapon
  - usedroptable: tipped_arrows_1
  - usedroptable: tipped_arrows_2
drop-table:
  bow_weapon:
    - BOW:
        equipped: 1.0
  tipped_arrows_1:
    - TIPPED_ARROW:
        equipped: 0.5
        nbt-data: ""
  tipped_arrows_2:
    - TIPPED_ARROW:
        equipped: 0.5
        nbt-data: ""
```
