### ISSUE TITLE
LM4: Reimplement Tiered Coloring

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/LevelledMobs#440]
Tiered Coloring needs to be reimplemented into LM4.

**Comment by lokka30** [comment]
Oath's Suggestion

***

The current nametag:

```yaml
'&8&l༺ &bLvl.%entity-level%&f %entity-prefix%&f%entity-name%&f%entity-suffix%&8 • &7%entity-health-rounded%&8/&7%entity-max-health-rounded%&c♥ &8&l༻'
```


Once we implement the tiered-coloring system, should replace the opening &b with %tiered%, with a &r added after the %entity-level% to reset any changes made with %tiered%. 
I also suggest we change the default color of the health text to a brighter color; ideally we can use the hex color code system &#123456 but if not I would suggest &b or &f instead.
There might also be the opportunity to create a modified %tiered%; transforming it to %tiered_name% which would allow the user to set their own colors based on the value of a fomula. An example of how this might be done in LM4's formatting:

```yaml
- action: 'set-tiered-placeholder'
  formula: '%entity-level%'
  placeholer: 'level-tier'
  tiers:
    '<=5': '&#22E76B'  # Green
    '6-10': '&#528CFF'  # Blue
    '11-15': '&#FFCD56' # Yellow
    '16-20': '&#F2003D' #Red
    '>=21': '&#B447FF'  # Purple
    default: '&f'  # White

- action: 'set-tiered-placeholder'
  formula: '%entity-health-rounded%/%entity-max-health-rounded%'
  placeholer: 'health-remaining'
  tiers:
    '<=0.3': '&#F2003D' #Red
    '0.31-0.70': '&#FFCD56' # Yellow
    '>=0.71': '&#22E76B'  # Green
    default: '&f'  # White
```
