### ISSUE TITLE
LM4 Suggestion: Swarm Mechanic

### ISSUE THREAD

**Issue by UltimaOath** [ArcanePlugins/LevelledMobs#441]
```yaml
  - function: 'activate-swarm-low-chance'
    triggers: ['on-entity-damage']
    processes:
      - process: 'engage-swarm'
        if:
          - condition: 'entity-type'
            in-list: ['zombie']
          - condition: 'entity-owner'
            not-in-list: []
          - condition: 'chance'
            value: 0.05
        do:
          - action: 'activate-swarm'
            duration: 5s
          - action: 'exit-function'
```

Was imagining a mechanic where if the `activate-swarm` action occurs, all entities within X distance of a player who caused the triggered event will be set to a follow range of the X distance plus 1, and will have their primary targets set to that player if the entity is not already following another player. This is to last for the set `duration:`, at which time the follow distance for those entities are then reset to their original values pre-swarm-event. If the entities have moved close enough to their target to naturally 'swarm' the player, then that's for the player to handle, but ideally the distance would mean that not the entire swarm would make it to the player before the duration ends. This would only apply to entities that presently exist and not future entities. Should a second swarm event occur, entities that are already/currently swarming are skipped for the new player.
