### ISSUE TITLE
Feature Request: add command toggle per player healthbar mobs and option in config 

### ISSUE THREAD

**Issue by Zarkness** [ArcanePlugins/LevelledMobs#449]
**Is your request related to a problem? Please describe it.
no

**Describe the solution you would like**
Add a command for users to disable the healthbar provided by the plugin and an option in the config to disable the healthbar directly above the mob

**Describe the alternatives you have considered** A clear and concise description of what you want to happen.
the command could be /levelledmobs healthbar toggle and the option could be healthbar: false

**Additional context**

**Comment by lokka30** [comment]
How come would you need this feature?

You can disable the name tag entirely by setting `nametag: 'disabled'`

**Comment by UltimaOath** [comment]
You can utilize the `permission:` condition in a custom rule to set the visibility per-player; by giving permission nodes to players that should/shouldn't see the nametags. I haven't tested this myself but it should theoretically work.

**Comment by UltimaOath** [comment]
```yaml
  - enabled: true
    name: 'Visibility based on Permission'
    conditions:
      permission: ['no_nametag']
    apply-settings:
      nametag-visibility-method: ['DISABLED']
```

Where `no_nametag` represents the permission node `levelledmobs.permission.no_nametag`.
