### ISSUE TITLE
LM3/4 - CustomDrops Points-Shop System

### ISSUE THREAD

**Issue by UltimaOath** [ArcanePlugins/LevelledMobs#453]
Original concept from Discord:
https://discord.com/channels/752310043214479462/756850940694495253/1040407787060076554

```yml
custom-rules:
  - enabled: true
    name: 'Give Points'

    conditions:
      chance: 0.25
      entities: ['ZOMBIE']
    apply-settings:
      give-points: 25

  - enabled: true
    name: 'Give Drop Tables'
    conditions:
      entities: ['ZOMBIE']
    apply-settings:
      use-droptable-id: weapon_shop_items, food_shop_items


drop-table:
  weapon_shop_items:
    - DIAMOND_SWORD:
        chance: 0.1
        points-required: 10
    - DIAMOND_BOOTS:
        chance: 0.01
        points-required: 15
  food_shop_items:
    - COOKED_PORK:
        chance: 0.15
        points-required: 7.5
```

Adding `give-points:` to Rules and `points-required:` in CustomDrops. Players earn a points value that is used to randomly select items that require those points to 'buy' behind the scenes. The drops are processed like normal and if it would have otherwise dropped, make sure the player has enough points and if so remove those points from total and process next item. Rinse and repeat until they either run out of points or items that need those points. Any left over points are carried over.
