### ISSUE TITLE
Maximum Equips

### ISSUE THREAD

**Issue by Ceddini** [ArcanePlugins/LevelledMobs#459]
**Is your feature request related to a problem? Please describe.**
I made a droptable of player heads and wanted only one of them to be equipped, but there's currently no way to do this, except having a super rare chance for each entry, which makes it impossible to have mobs always equipped with a head.

**Describe the solution you'd like**
Much like the "maxdropgroup", a "maxequipgroup" would be very useful. That way only X equippable items would be chosen.

**Describe alternatives you've considered**
I thought that a cumulative chance setting / weighted setting could be nice as well. So instead of every entry rolling (except with maxdropgroup/maxequipgroup set), all chances would need to add up to 1 or the chance setting would act as weights instead. 
That way only one of the entries in the group can run and at least when using weights, setting up chances might be a lot easier.

**Additional context**
None

**Comment by UltimaOath** [comment]
Current sample yaml of idea fleshed out.

```yaml
# Change 'maxdropgroup' to 'group-limits'
# Include 'drop', 'equip', and 'amount' as a subset of 'group-limits'
# If 'maxdropgroup' was present in config, take the value and input as value for subset 'drop'
# A value of '-1' eliminates the groupid check for that option; a value of '0' means zero items when used.

defaults:
  groupid: diamond_hands
  group-limits:
    drop: 1
    equip: 1
    amount: -1

drop-table:
  demo_table:
    - DIAMOND:
        groupid: 'diamond_hands'
        maxdropgroup: 5  # Old Method, replaced with:

        group-limits:  # Convert maxdropgroup into 'group-limits', move maxdropgroup value to new 'drop' config option as a subset of 'group-limits'
          drop: 5  # Replaces 'maxdropgroup', moved to here
          equip: 1  # Limits number of equipped items from same group
          amount: -1  # Limits the 'amount' value of any item in the group


# As for 'weighted chance', I suggest the new config option 'chance-weighted' which when specified would gather all items of the same groupid, sort the items by their chance weights, and then randomly select an item. This item will then have their 'chance' processed to determine whether it will drop. This mechanism can also be applied to 'equipped' making a 'weighted equip' which processes in essentially the same manner. 'equipped-weighted' would gather all items of the same groupid, sort by their equipped weights, and then randomly select; then their specified 'equipped' chance will determine whether it will or will not equip. When combined with the above groupid limiter it will prevent unintended equips. 

  demo_table:
    - DIAMOND:
        chance: 0.2
        chance-weighted: 5  # New Method; functions similar to Weighted Random tiers for strategies
        equipped: 0.5
        equipped-weighted: 3  # New Method
```
