### ISSUE TITLE
Condition "Permission" Not Applying To Rules

### ISSUE THREAD

**Issue by KowalskiXCIX** [ArcanePlugins/LevelledMobs#463]
**Describe the bug**
When using the "permission" condition in custom rules, it isn't applying, after numerous attempts and working with some discord Admins/Devs, we ran into the following issue:

The intention is to have multiple permission groups for users who want harder difficulties / different levels

**Steps to Reproduce**
Implement a "permission:" condition in any ruleset

**Expected behavior**
The rule would meet the condition that is provided, Example: if permission: ['owner'] was applied and a user had the ['owner'] permission in luck perms, it would apply the mob level, applying the permission "levelledmobs.permission.owner" in luck perms to the desired group of users, which would then activate the rest of the rules applied in the custom rule config

**Server software**
Paper

**Server version**
Minecraft 1.20.2

**LevelledMobs version**
LevelledMobs version 3.12.1 b781

Config File
```
- enabled: true
    name: 'Custom Leveling Hardmode'
    conditions:
      permission: ['owner', 'Owner']
    strategies:
      player-levelling:
        enabled: true
        match-level: false
        use-player-max-level: false
        decrease-level: true
        recheck-players: false
        preserve-entity: 10s
        player-level-scale: 1.0
        level-cap: 50
        merge: false
        tiers:
          1-10: 1-10
          11-20: 1-20
          21-30: 1-30
          31-40: 1-40
          41-50: 1-50
        variable: '%level%'
    apply-settings:
      nametag: '&8%tiered%Lvl %mob-lvl%&8 | &f%displayname%&8 | &f%entity-health-rounded% %tiered%%heart_symbol% &r%health-indicator% &8'
      tiered-coloring:
        1-10: '&#22E76B' #Green
        11-20: '&#528CFF' #Blue
        10-30: '&#FFCD56' #Yellow
        31-40: '&#FE803C' #Orange
        41-50: '&#F2003D' #Red
      multipliers:
        max-health: 0.15
        movement-speed: 0.015
        attack-damage: 0.15
        ranged-attack-damage: 0.015
        creeper-blast-damage: 0.015
        item-drop: 0.25
        xp-drop: 0.25
```

Console Log
```
[25.10 11:13:36] [Server] [INFO] LevelledMobs: [Debug: PLAYER_LEVELLING] mob: ZOMBIE, player: Kowantify, lvl-src: 15.0 (spawn), lvl-scale: 15, tier: 11-20 [1, 20], cap: 50, result: [1, 20]
[25.10 11:13:36] [Server] [INFO] LevelledMobs: [Debug: PLAYER_LEVELLING] mob: CREEPER, player: Kowantify, lvl-src: 15.0 (spawn), lvl-scale: 15, tier: 11-20 [1, 20], cap: 50, result: [1, 20]
[25.10 11:13:36] [Server] [INFO] LevelledMobs: [Debug: PLAYER_LEVELLING] mob: SKELETON, player: Kowantify, lvl-src: 15.0 (spawn), lvl-scale: 15, tier: 11-20 [1, 20], cap: 50, result: [1, 20]
[25.10 11:13:36] [Server] [INFO] LevelledMobs: [Debug: PLAYER_LEVELLING] mob: SKELETON, player: Kowantify, lvl-src: 15.0 (spawn), lvl-scale: 15, tier: 11-20 [1, 20], cap: 50, result: [1, 20]
[25.10 11:13:36] [Server] [INFO] LevelledMobs: [Debug: DENIED_RULE_PERMISSION] Custom Leveling Hardmode, mob: ZOMBIE, no player was provided
[25.10 11:13:36] [Server] [INFO] LevelledMobs: [Debug: DENIED_RULE_PERMISSION] Custom Leveling Hardmode, mob: ZOMBIE, no player was provided
[25.10 11:13:36] [Server] [INFO] LevelledMobs: [Debug: DENIED_RULE_PERMISSION] Custom Leveling Hardmode, mob: ZOMBIE, no player was provided
[25.10 11:13:36] [Server] [INFO] LevelledMobs: [Debug: DENIED_RULE_PERMISSION] Custom Leveling Hardmode, mob: ZOMBIE, no player was provided
[25.10 11:13:36] [Server] [INFO] LevelledMobs: [Debug: DENIED_RULE_PERMISSION] Custom Leveling Hardmode, mob: SKELETON, no player was provided
[25.10 11:13:36] [Server] [INFO] LevelledMobs: [Debug: DENIED_RULE_PERMISSION] Custom Leveling Hardmode, mob: SKELETON, no player was provided
[25.10 11:13:36] [Server] [INFO] LevelledMobs: [Debug: DENIED_RULE_PERMISSION] Custom Leveling Hardmode, mob: ZOMBIE, no player was provided
[25.10 11:13:39] [Server] [INFO] LevelledMobs: [Debug: DENIED_RULE_PERMISSION] Custom Leveling Hardmode, mob: ZOMBIE, no player was provided
[25.10 11:13:39] [Server] [INFO] LevelledMobs: [Debug: DENIED_RULE_PERMISSION] Custom Leveling Hardmode, mob: ZOMBIE, no player was provided
[25.10 11:13:39] [Server] [INFO] LevelledMobs: [Debug: DENIED_RULE_PERMISSION] Custom Leveling Hardmode, mob: ZOMBIE, no player was provided
[25.10 11:13:39] [Server] [INFO] LevelledMobs: [Debug: DENIED_RULE_PERMISSION] Custom Leveling Hardmode, mob: ZOMBIE, no player was provided
```

Luck Perms Screenshot:
![Luck Perms levelled Mobs Permission - 10-25-2023](https://github.com/ArcanePlugins/LevelledMobs/assets/35680697/35abbcd5-64b9-4a78-a382-9dd03110eeea)

Snippet from permission condition wiki
`
permission: | A MODALLIST config option; this represents a check against the nearest player to the entity, OR the player who killed an entity, depending on it's implementation. All permissions as registered as levelledmobs.permission.<node>, where <node> represents the value of this config. For example, if your permission was levelledmobs.permission.vip, you would configure it as such: permission: ['vip'].
`
