### ISSUE TITLE
Player Selectable Tier / Rules (pre-defined

### ISSUE THREAD

**Issue by KowalskiXCIX** [ArcanePlugins/LevelledMobs#464]
**Is your feature request related to a problem? Please describe.**
I'm running into the issue of attempting to have players be able to select their own rules / difficulty level with levelled mobs custom rules

**Describe the solution you'd like**
Currently on my server I have 3 buttons that have generic names such as "easy, medium, and hard" and these buttons would apply a luck perms permission to that specific player, which then PAPI would read that as true false, meaning I would need 3 rules essentially for each "difficulty" level, this seemed to be very finicky, and only worked for one ruleset at a time, which is where I stumbled into many issues, I attempted a slew of fixed and ideas, but all didn't meet my primary ideas, the ability for the players to select their desired experience, on a permission level

How the buttons work is the "easy button" will apply the "levelledmobs.difficulty.easy" permission, which will in turn, make the nearest mobs to that player, read from the pre-defined ruleset in the config, IE: a rulset that has a condition setting called "difficulty-selector" which is where you would tie the name of the difficulty, 

This is something I would like implemented, it could have a different name, but this is a very generic idea of how it might look in the "config", so whenever a player has the permission "Hard" they will get the rule that is tied with that "condition" applied, meaning any variable can be used on top of that permission allowing for a lot more control
Example:
```
 - enabled: true
    name: 'Custom Levelling Hard'

#THE CUSTOM CONDITION BELOW
    condition:  
      difficulty-selector: 'Hard'

    strategies:
      player-levelling:
        enabled: true
        match-level: false
        use-player-max-level: false
        decrease-level: true
        recheck-players: false
        preserve-entity: 10s
        player-level-scale: 1.0
        level-cap: 50
        merge: false
        tiers:
          1-10: 1-10
        11-20: 11-20
        10-30: 10-30
        31-40: 31-40:
        41-50: 41-50
        variable: '%level%'
```

**Describe alternatives you've considered**
I've attempted to use multiple different PAPI placeholders, and with the support of strings it is proving to be very difficult to implement proper rules that include more then just a "yes / no" tier, this would allow for multiple different difficulty levels up to the server owner, and that lets the players decide their own experience

**Comment by UltimaOath** [comment]
Initial first thoughts: https://discord.com/channels/752310043214479462/756850940694495253/1167129863606501446

A new placeholder, `%levelledmobs_player-option%`, which refers to a new command `/lm enable` (Default) or `/lm disable`. For Ops `/lm enable <player>`, `/lm enable all`, `/lm disable <player>`, `/lm disable all`. This placeholder can be used to populate the Player Level Modifier system with options to pick from. Good for simple off/on setup.

A new config option to use in custom rules or in default rule, which looks like `player-optional: ['TRUE', 'Name']`; The first option being whether the rule is enabled or disabled by default for players, and the second option being the plaintext name of the rule which players are selecting from as options via the command `/lm rules optional <name> enabled` or `/lm rules optional <name> disabled` ; For Ops `/lm rules optional <name/all> enabled`, `/lm rules optional <name/all> enabled <player>`, `/lm rules optional <name/all> disabled`, `/lm rules optional <name/all> disabled <player>`.

```yaml
  - enabled: true
    name: 'New Player Optional Rule'
    condition:  
      player-optional: ['TRUE', 'MC Level Based Mobs']
    strategies:
      player-levelling:
        enabled: true
        match-level: false
        use-player-max-level: false
        decrease-level: true
        recheck-players: false
        preserve-entity: 10s
        player-level-scale: 1.0
        level-cap: 50
        merge: false
        tiers:
          1-10: 1-10
          11-20: 11-20
          10-30: 10-30
          31-40: 31-40
          41-50: 41-50
        variable: '%level%'

  - enabled: true
    name: 'New Player Optional Rule 2'
    condition:  
      player-optional: ['FALSE', 'Weighted Random']
    strategies:
      weighted-random: true
```

This outputs the following command options: `/lm rules optional "MC Level Based Mobs" enabled` `/lm rules optional "Weighted Random" enabled` etc. The idea: Rules are optionally turned off and on for players. If a player enables a rule for themselves, it is re-evaluated at the next async task and working in a similar fashion to how Player Level Modifier updates levels for players it can update rules applied to nearby entities for the closest players?

Might even incorporate the `permission` command so that only the rules available to specific player roles are available for off/on
